spring:
  datasource:
    url:
      jdbc:postgresql://localhost:11380/studs
    username:

    password:

  jpa:
    hibernate:
      ddl-auto:
        validate
server:
  servlet:
    contextPath:
      /api
jwt:
  secret:
    53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
