DROP TABLE person CASCADE;
DROP TABLE action CASCADE;
DROP TABLE scene CASCADE;
DROP TABLE object CASCADE;
DROP TABLE material CASCADE;
DROP TABLE object_material CASCADE;
DROP TABLE feeling CASCADE;
DROP TABLE person_feeling CASCADE;